name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Deploy to Nexus Snapshots (Uncomment to enable deployment)
      - name: Deploy to Nexus Snapshots
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }} # Nexus username stored as a secret
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }} # Nexus password stored as a secret
        run: |
          mvn deploy -DskipTests \
          -DaltDeploymentRepository=nexus-snapshots::default::http://localhost:8081/repository/maven-snapshots/ \
          -Dnexus.username=$NEXUS_USERNAME \
          -Dnexus.password=$NEXUS_PASSWORD

      # Step 5: Build and push Docker image
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: saitej150/spring-security
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}